unit = [
    ["UniteDescriptor", "export",""], 
    ["ClassNameForDebug", "ClassNameForDebug",""],
    ["Nationalite", "Nationalite",""],
    ["MotherCountry", "MotherCountry", ""],
    ["UnitConcealmentBonus", "UnitConcealmentBonus", 0.0],
    ["ArmorDescriptorFront", "ArmorDescriptorFront",""],
    ["ArmorDescriptorSides", "ArmorDescriptorSides",""],
    ["ArmorDescriptorRear", "ArmorDescriptorRear", ""],
    ["ArmorDescriptorTop", "ArmorDescriptorTop", ""],
    ["MaxDamages", "MaxDamages",0.0],
    ["HitRollECM", "HitRollECM",0.0],
    ["Dangerousness", "Dangerousness  =",0.0],
    ["MaxSpeed","MaxSpeed", 0], #Metre
    ["RoadSpeed"," RoadSpeed", 0],
    ["SpeedBonusOnRoad","SpeedBonusOnRoad", 0.0],
    ["MaxAcceleration","MaxAcceleration", 0.0], #Metre
    ["MaxDeceleration","MaxDeceleration", 0.0], #Metre
    ["TempsDemiTour","TempsDemiTour", 0.0],
    ["FuelCapacity","FuelCapacity", 0],
    ["FuelMoveDuration","FuelMoveDuration", 0],
    ["Autonomy","Autonomy", 0.0],
    ["OpticalStrength","OpticalStrength", 0],
    ["OpticalStrengthAltitude","OpticalStrengthAltitude", 0],
    ["IdentifyBaseProbability","IdentifyBaseProbability", 0.0],
    ["TimeBetweenEachIdentifyRoll","TimeBetweenEachIdentifyRoll", 0.0],
    ["ProductionYear","ProductionYear", 0],
    ["IsTransporter","IsTransporter", False],
    ["IsPlane","IsPlane", False],
    ["UnitAttackValue","UnitAttackValue", 0],
    ["UnitDefenseValue","UnitDefenseValue", 0],
    ["EvacuationTime","EvacuationTime", 0],
    ["TravelDuration","TravelDuration", 0],
    ["RoleList", "RoleList", ""], #Built like array
    ["SpecialtiesList", "SpecialtiesList", []],
    ["Factory", "Factory", ""],
    ["Resource_CommandPoints", "Resource_CommandPoints", 0],
    ["UpgradeFromUnit", "UpgradeFromUnit", ""],
    ["SupplyCapacity", "SupplyCapacity", 0],
    ["UnlockableOrders", "UnlockableOrders", ""], #Reference to other file
    ["WeaponDescriptor", "WeaponDescriptor", ""],
    ["SupplyCapacity", "SupplyCapacity", 0.0],
    ["AltitudeMin", "AltitudeMin", 0.0], #Metre
    ["Altitude", " Altitude =", 0.0], #Metre
    ["AgilityRadius", "AgilityRadius", 0.0], #Metre
    ["PitchAngle", "PitchAngle", 0.0],
    ["RollAngle", "RollAngle", 0.0],
    ["RollSpeed", "RollSpeed =", 0.0],
    ["UpwardSpeed", "UpwardSpeed", 0.0], #Metre
    ["TorqueManoeuvrability", "TorqueManoeuvrability", 0.0],
    ["CyclicManoeuvrability", "CyclicManoeuvrability", 0.0],
    ["MaxInclination", "MaxInclination", 0.0],
    ["GFactorLimit", "GFactorLimit", 0.0],
    ["RotorArea", "RotorArea", 0.0],
    ["AltitudeMax", "AltitudeMax", 0.0],
    ["PitchSpeed", "PitchSpeed", 0.0],
    ["AltitudeMinForRoll", "AltitudeMinForRoll", 0.0],
    ["MinRollSpeedForRoll", "MinRollSpeedForRoll", 0.0],
]

weapon = [
    ["WeaponDescriptor", "export",""], 
    ["Salves", "Salves", []], #Built like array
    ["HasMainSalvo", "HasMainSalvo", False],
    ["SalvoIsMainSalvo", "SalvoIsMainSalvo", []], #Built like array
    ["Turret_1_AngleRotationMax", "AngleRotationMax", None],
    ["Turret_1_AngleRotationMaxPitch", "AngleRotationMaxPitch", None],
    ["Turret_1_AngleRotationMinPitch", "AngleRotationMinPitch", None],
    ["Turret_1_VitesseRotation", "VitesseRotation", None],
    ["Turret_1_Weapon_1_Ammunition", "Ammunition", None],
    ["Turret_1_Weapon_1_NbWeapons", "NbWeapons", None],
    ["Turret_1_Weapon_1_SalvoStockIndex", "SalvoStockIndex", None],
    ["Turret_1_Weapon_2_Ammunition", "Ammunition", None],
    ["Turret_1_Weapon_2_NbWeapons", "NbWeapons", None],
    ["Turret_1_Weapon_2_SalvoStockIndex", "SalvoStockIndex", None],
    ["Turret_1_Weapon_3_Ammunition", "Ammunition", None],
    ["Turret_1_Weapon_3_NbWeapons", "NbWeapons", None],
    ["Turret_1_Weapon_3_SalvoStockIndex", "SalvoStockIndex", None],
    ["Turret_2_AngleRotationMax", "AngleRotationMax", None],
    ["Turret_2_AngleRotationMaxPitch", "AngleRotationMaxPitch", None],
    ["Turret_2_AngleRotationMinPitch", "AngleRotationMinPitch", None],
    ["Turret_2_VitesseRotation", "VitesseRotation", None],
    ["Turret_2_Weapon_1_Ammunition", "Ammunition", None],
    ["Turret_2_Weapon_1_NbWeapons", "NbWeapons", None],
    ["Turret_2_Weapon_1_SalvoStockIndex", "SalvoStockIndex", None],
    ["Turret_3_AngleRotationMax", "AngleRotationMax", None],
    ["Turret_3_AngleRotationMaxPitch", "AngleRotationMaxPitch", None],
    ["Turret_3_AngleRotationMinPitch", "AngleRotationMinPitch", None],
    ["Turret_3_VitesseRotation", "VitesseRotation", None],
    ["Turret_3_Weapon_1_Ammunition", "Ammunition", None],
    ["Turret_3_Weapon_1_NbWeapons", "NbWeapons", None],
    ["Turret_3_Weapon_1_SalvoStockIndex", "SalvoStockIndex", None],
    ["Turret_4_AngleRotationMax", "AngleRotationMax", None],
    ["Turret_4_AngleRotationMaxPitch", "AngleRotationMaxPitch", None],
    ["Turret_4_AngleRotationMinPitch", "AngleRotationMinPitch", None],
    ["Turret_4_VitesseRotation", "VitesseRotation", None],
    ["Turret_4_Weapon_1_Ammunition", "Ammunition", None],
    ["Turret_4_Weapon_1_NbWeapons", "NbWeapons", None],
    ["Turret_4_Weapon_1_SalvoStockIndex", "SalvoStockIndex", None],
    ["Turret_5_AngleRotationMax", "AngleRotationMax", None],
    ["Turret_5_AngleRotationMaxPitch", "AngleRotationMaxPitch", None],
    ["Turret_5_AngleRotationMinPitch", "AngleRotationMinPitch", None],
    ["Turret_5_VitesseRotation", "VitesseRotation", None],
    ["Turret_5_Weapon_1_Ammunition", "Ammunition", None],
    ["Turret_5_Weapon_1_NbWeapons", "NbWeapons", None],
    ["Turret_5_Weapon_1_SalvoStockIndex", "SalvoStockIndex", None]
]
